/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.piminimenercado.tela;

import com.mycompany.piminimenercado.Funcionario;
import com.mycompany.piminimenercado.tela.TelaProdutos;
import com.mycompany.piminimenercado.tela.TelaRegistro;
import com.mycompany.piminimenercado.tela.TelaVenda;

/**
 *
 * @author joaov
 */
public class TelaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal(Funcionario f) {
        initComponents();
        this.setLocationRelativeTo(null);
        String nivel = f.getNivel() != null? f.getNivel().toLowerCase() :"";
        switch(nivel) {
        case "gerente":
            jButtonProduto.setEnabled(true);
            jButtonFuncionario.setEnabled(true);
            jButtonVenda.setEnabled(true);
            jButtonRegistro.setEnabled(true);
            break;
        case "atendente":
            jButtonProduto.setEnabled(false);
            jButtonFuncionario.setEnabled(false);
            jButtonVenda.setEnabled(true);
            jButtonRegistro.setEnabled(false);
            break;
        default:
            jButtonProduto.setEnabled(false);
            jButtonFuncionario.setEnabled(false);
            jButtonVenda.setEnabled(false);
            jButtonRegistro.setEnabled(false);
            break;
    }
}

    public TelaPrincipal(){
        initComponents();
        
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButtonProduto = new javax.swing.JButton();
        jButtonFuncionario = new javax.swing.JButton();
        jButtonVenda = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButtonRegistro = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));

        jButtonProduto.setBackground(new java.awt.Color(153, 153, 153));
        jButtonProduto.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jButtonProduto.setForeground(new java.awt.Color(0, 0, 0));
        jButtonProduto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/caixa-de-entrega.png"))); // NOI18N
        jButtonProduto.setText(" Cadastrar Produtos");
        jButtonProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonProdutoActionPerformed(evt);
            }
        });

        jButtonFuncionario.setBackground(new java.awt.Color(153, 153, 153));
        jButtonFuncionario.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jButtonFuncionario.setForeground(new java.awt.Color(0, 0, 0));
        jButtonFuncionario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/adicionar-usuario.png"))); // NOI18N
        jButtonFuncionario.setText(" Cadastrar Funcionário");
        jButtonFuncionario.setMaximumSize(new java.awt.Dimension(260, 112));
        jButtonFuncionario.setMinimumSize(new java.awt.Dimension(260, 112));
        jButtonFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFuncionarioActionPerformed(evt);
            }
        });

        jButtonVenda.setBackground(new java.awt.Color(153, 153, 153));
        jButtonVenda.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jButtonVenda.setForeground(new java.awt.Color(0, 0, 0));
        jButtonVenda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/dolar.png"))); // NOI18N
        jButtonVenda.setText("  Venda");
        jButtonVenda.setMaximumSize(new java.awt.Dimension(260, 112));
        jButtonVenda.setMinimumSize(new java.awt.Dimension(260, 112));
        jButtonVenda.setPreferredSize(new java.awt.Dimension(260, 112));
        jButtonVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVendaActionPerformed(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(102, 102, 102));
        jLabel1.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/logo1_2.png"))); // NOI18N

        jButtonRegistro.setBackground(new java.awt.Color(153, 153, 153));
        jButtonRegistro.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jButtonRegistro.setForeground(new java.awt.Color(0, 0, 0));
        jButtonRegistro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/contabilidade (1).png"))); // NOI18N
        jButtonRegistro.setText(" Registro Venda");
        jButtonRegistro.setMaximumSize(new java.awt.Dimension(260, 112));
        jButtonRegistro.setMinimumSize(new java.awt.Dimension(260, 112));
        jButtonRegistro.setPreferredSize(new java.awt.Dimension(260, 112));
        jButtonRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRegistroActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonProduto)
                    .addComponent(jButtonVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 154, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonRegistro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonFuncionario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(63, 63, 63))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(358, 358, 358)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonProduto)
                    .addComponent(jButtonFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonVenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(74, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonProdutoActionPerformed
        TelaProdutos tp = new TelaProdutos();
        tp.setVisible(true);
        
    }//GEN-LAST:event_jButtonProdutoActionPerformed

    private void jButtonFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFuncionarioActionPerformed
       TelaFuncionario tf = new TelaFuncionario();
       tf.setVisible(true);
    }//GEN-LAST:event_jButtonFuncionarioActionPerformed

    private void jButtonVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVendaActionPerformed
        TelaVenda tv = new TelaVenda();
        tv.setVisible(true);
    }//GEN-LAST:event_jButtonVendaActionPerformed

    private void jButtonRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRegistroActionPerformed
        TelaRegistro tr = new TelaRegistro();
        tr.setVisible(true);
    }//GEN-LAST:event_jButtonRegistroActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonFuncionario;
    private javax.swing.JButton jButtonProduto;
    private javax.swing.JButton jButtonRegistro;
    private javax.swing.JButton jButtonVenda;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
